name: ci/cd

on:
  push:
    branches: [main]
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: ./bin/make ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    runs-on: ubuntu-latest
    needs: [ci]
    if: ${{ github.event_name == 'push' }} # only run on push to main
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: ./bin/make release
        env:
          GITHUB_APP_ID: ${{ secrets.EVYLANGBOT_GITHUB_APP_ID }}
          GITHUB_APP_PEM: ${{ secrets.EVYLANGBOT_GITHUB_APP_PEM }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
